"""initial transactional schema

Revision ID: 098980d3b316
Revises:
Create Date: 2026-08-30 01:14:11.556781
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "098980d3b316"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("organization", sa.String(length=256), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("license", sa.String(length=256), nullable=False),
        sa.Column("redistribution_status", sa.String(length=64), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("authoritative", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "nutrients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("canonical_unit", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email_normalized", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "role",
            sa.Enum("STUDENT", "ADULT", "ADMIN", name="role", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_email_normalized"), ["email_normalized"], unique=True
        )

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_events_actor_user_id"), ["actor_user_id"], unique=False
        )

    op.create_table(
        "consent_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("document_version", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=64), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consent_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_consent_records_user_id"), ["user_id"], unique=False)

    op.create_table(
        "foods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("food_code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_food_id", sa.String(length=128), nullable=False),
        sa.Column("edible_fraction", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("authoritative", sa.Boolean(), nullable=False),
        sa.Column("dietary_tags", sa.JSON(), nullable=False),
        sa.Column("allergens", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("food_code"),
    )
    with op.batch_alter_table("foods", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_foods_name"), ["name"], unique=False)

    op.create_table(
        "meals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("eaten_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("meals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_meals_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_meals_user_local_date", ["user_id", "local_date"], unique=False)

    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("source_sex_category", sa.String(length=32), nullable=True),
        sa.Column("activity_level", sa.String(length=32), nullable=True),
        sa.Column("dietary_pattern", sa.String(length=32), nullable=False),
        sa.Column("allergens", sa.JSON(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_profiles_user_id"), ["user_id"], unique=True)

    op.create_table(
        "recommendation_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("candidate_id", sa.String(length=128), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("trace", sa.JSON(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommendation_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendation_decisions_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "refresh_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("refresh_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_sessions_family_id"), ["family_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_sessions_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_refresh_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "target_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_rule_id", sa.String(length=128), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("nutrient_id", sa.Uuid(), nullable=False),
        sa.Column("rda", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("ear", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("tul", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("minimum_age", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("maximum_age_exclusive", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("source_sex_category", sa.String(length=32), nullable=True),
        sa.Column("activity_level", sa.String(length=32), nullable=True),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["nutrient_id"],
            ["nutrients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_id", "external_rule_id", "version", name="uq_target_rule_version"
        ),
    )
    op.create_table(
        "target_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("profile_revision", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("provisional", sa.Boolean(), nullable=False),
        sa.Column("trace", sa.JSON(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "profile_revision", "model_version", name="uq_target_snapshot_input"
        ),
    )
    with op.batch_alter_table("target_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_target_snapshots_user_id"), ["user_id"], unique=False)

    op.create_table(
        "food_nutrients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("food_id", sa.Uuid(), nullable=False),
        sa.Column("nutrient_id", sa.Uuid(), nullable=False),
        sa.Column("amount_per_100g", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("canonical_unit", sa.String(length=16), nullable=False),
        sa.Column("value_status", sa.String(length=32), nullable=False),
        sa.Column("missing_reason", sa.String(length=64), nullable=True),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["food_id"], ["foods.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["nutrient_id"],
            ["nutrients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("food_id", "nutrient_id", "source_version"),
    )
    op.create_table(
        "meal_ingredients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("food_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_g", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("edible_fraction_override", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["foods.id"],
        ),
        sa.ForeignKeyConstraint(["meal_id"], ["meals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "target_values",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("nutrient_id", sa.Uuid(), nullable=False),
        sa.Column("target_rule_id", sa.Uuid(), nullable=False),
        sa.Column("rda", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("ear", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("tul", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("canonical_unit", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["nutrient_id"],
            ["nutrients.id"],
        ),
        sa.ForeignKeyConstraint(["snapshot_id"], ["target_snapshots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["target_rule_id"],
            ["target_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "nutrient_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("target_values")
    op.drop_table("meal_ingredients")
    op.drop_table("food_nutrients")
    with op.batch_alter_table("target_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_target_snapshots_user_id"))

    op.drop_table("target_snapshots")
    op.drop_table("target_rules")
    with op.batch_alter_table("refresh_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_token_hash"))
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_family_id"))

    op.drop_table("refresh_sessions")
    with op.batch_alter_table("recommendation_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendation_decisions_user_id"))

    op.drop_table("recommendation_decisions")
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profiles_user_id"))

    op.drop_table("profiles")
    with op.batch_alter_table("meals", schema=None) as batch_op:
        batch_op.drop_index("ix_meals_user_local_date")
        batch_op.drop_index(batch_op.f("ix_meals_user_id"))

    op.drop_table("meals")
    with op.batch_alter_table("foods", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_foods_name"))

    op.drop_table("foods")
    with op.batch_alter_table("consent_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consent_records_user_id"))

    op.drop_table("consent_records")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_user_id"))

    op.drop_table("audit_events")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email_normalized"))

    op.drop_table("users")
    op.drop_table("nutrients")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
