"""add idempotent recompute jobs

Revision ID: 3e3eeacd57ce
Revises: 098980d3b316
Create Date: 2026-08-30 01:17:03.672129
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3e3eeacd57ce"
down_revision: str | Sequence[str] | None = "098980d3b316"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recompute_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("affected_date", sa.Date(), nullable=False),
        sa.Column("input_revision", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("result_trace", sa.JSON(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "affected_date",
            "input_revision",
            "model_version",
            name="uq_recompute_job_input",
        ),
    )
    with op.batch_alter_table("recompute_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recompute_jobs_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recompute_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recompute_jobs_user_id"))

    op.drop_table("recompute_jobs")
    # ### end Alembic commands ###
